# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}  # Allows manual trigger from GitHub Actions UI
  schedule:
    - cron: '18 16 * * *'

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@main

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: devskim-results.sarif
